/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mik_adim_jni_files_FileUtils */

#ifndef _Included_com_mik_adim_jni_files_FileUtils
#define _Included_com_mik_adim_jni_files_FileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mik_adim_jni_files_FileUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mik_adim_jni_1files_FileUtils_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
